added OpenMapTiles and OSMNames
javnik36/awesome-osm pull request #1
Opened 2018-01-05 08:58 UTC by xkomczax

2018-01-06 13:52 UTC, javnik36 requested changes

2018-01-06 13:52 UTC, javnik36 commented on readme.md
> +* [OpenMapTiles](https://github.com/openmaptiles) - Set of tools for self-hosted vector maps and map services.
Maybe change here to [Tools](https://github.com/openmaptiles/openmaptiles-tools)? And add [full site](https://openmaptiles.org/) to Full-site projects? What do you think?

2018-01-08 13:39 UTC, xkomczax commented
Thanks for your suggestion. Is this OK?

2018-01-08 17:00 UTC, javnik36 approved these changes

2018-01-08 17:02 UTC, merged

2018-01-08 17:03 UTC, javnik36 commented
Yes, OK :) Thanks for help 👍